/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvogadoRouteImport } from './routes/advogado'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdvogadoDashboardRouteImport } from './routes/advogado.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadoRoute = AdvogadoRouteImport.update({
  id: '/advogado',
  path: '/advogado',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadoDashboardRoute = AdvogadoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdvogadoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/login': typeof LoginRoute
  '/advogado/dashboard': typeof AdvogadoDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/login': typeof LoginRoute
  '/advogado/dashboard': typeof AdvogadoDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/login': typeof LoginRoute
  '/advogado/dashboard': typeof AdvogadoDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advogado' | '/cliente' | '/login' | '/advogado/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advogado' | '/cliente' | '/login' | '/advogado/dashboard'
  id:
    | '__root__'
    | '/'
    | '/advogado'
    | '/cliente'
    | '/login'
    | '/advogado/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadoRoute: typeof AdvogadoRouteWithChildren
  ClienteRoute: typeof ClienteRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogado': {
      id: '/advogado'
      path: '/advogado'
      fullPath: '/advogado'
      preLoaderRoute: typeof AdvogadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogado/dashboard': {
      id: '/advogado/dashboard'
      path: '/dashboard'
      fullPath: '/advogado/dashboard'
      preLoaderRoute: typeof AdvogadoDashboardRouteImport
      parentRoute: typeof AdvogadoRoute
    }
  }
}

interface AdvogadoRouteChildren {
  AdvogadoDashboardRoute: typeof AdvogadoDashboardRoute
}

const AdvogadoRouteChildren: AdvogadoRouteChildren = {
  AdvogadoDashboardRoute: AdvogadoDashboardRoute,
}

const AdvogadoRouteWithChildren = AdvogadoRoute._addFileChildren(
  AdvogadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadoRoute: AdvogadoRouteWithChildren,
  ClienteRoute: ClienteRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
