/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvogadoRouteImport } from './routes/advogado'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdvogadoAgendaRouteImport } from './routes/advogado.agenda'
import { Route as AdvogadoAssistenteRouteImport } from './routes/advogado.assistente'
import { Route as AdvogadoCasosRouteImport } from './routes/advogado.casos'
import { Route as AdvogadoClientesRouteImport } from './routes/advogado.clientes'
import { Route as AdvogadoDashboardRouteImport } from './routes/advogado.dashboard'
import { Route as AdvogadoDocumentosRouteImport } from './routes/advogado.documentos'
import { Route as AdvogadoNotificacoesRouteImport } from './routes/advogado.notificacoes'
import { Route as AdvogadoProcessosRouteImport } from './routes/advogado.processos'
import { Route as ClienteAssistenteRouteImport } from './routes/cliente.assistente'
import { Route as AdvogadoClientesIdRouteImport } from './routes/advogado.clientes.$id'
import { Route as AdvogadoProcessosIdRouteImport } from './routes/advogado.processos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadoRoute = AdvogadoRouteImport.update({
  id: '/advogado',
  path: '/advogado',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadoAgendaRoute = AdvogadoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoAssistenteRoute = AdvogadoAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoCasosRoute = AdvogadoCasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoClientesRoute = AdvogadoClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoDashboardRoute = AdvogadoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoDocumentosRoute = AdvogadoDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoNotificacoesRoute = AdvogadoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdvogadoRoute,
} as any)
const AdvogadoProcessosRoute = AdvogadoProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AdvogadoRoute,
} as any)
const ClienteAssistenteRoute = ClienteAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => ClienteRoute,
} as any)
const AdvogadoClientesIdRoute = AdvogadoClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdvogadoClientesRoute,
} as any)
const AdvogadoProcessosIdRoute = AdvogadoProcessosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdvogadoProcessosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/advogado/agenda': typeof AdvogadoAgendaRoute
  '/advogado/assistente': typeof AdvogadoAssistenteRoute
  '/advogado/casos': typeof AdvogadoCasosRoute
  '/advogado/clientes': typeof AdvogadoClientesRouteWithChildren
  '/advogado/dashboard': typeof AdvogadoDashboardRoute
  '/advogado/documentos': typeof AdvogadoDocumentosRoute
  '/advogado/notificacoes': typeof AdvogadoNotificacoesRoute
  '/advogado/processos': typeof AdvogadoProcessosRouteWithChildren
  '/cliente/assistente': typeof ClienteAssistenteRoute
  '/advogado/clientes/$id': typeof AdvogadoClientesIdRoute
  '/advogado/processos/$id': typeof AdvogadoProcessosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/advogado/agenda': typeof AdvogadoAgendaRoute
  '/advogado/assistente': typeof AdvogadoAssistenteRoute
  '/advogado/casos': typeof AdvogadoCasosRoute
  '/advogado/clientes': typeof AdvogadoClientesRouteWithChildren
  '/advogado/dashboard': typeof AdvogadoDashboardRoute
  '/advogado/documentos': typeof AdvogadoDocumentosRoute
  '/advogado/notificacoes': typeof AdvogadoNotificacoesRoute
  '/advogado/processos': typeof AdvogadoProcessosRouteWithChildren
  '/cliente/assistente': typeof ClienteAssistenteRoute
  '/advogado/clientes/$id': typeof AdvogadoClientesIdRoute
  '/advogado/processos/$id': typeof AdvogadoProcessosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogado': typeof AdvogadoRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/advogado/agenda': typeof AdvogadoAgendaRoute
  '/advogado/assistente': typeof AdvogadoAssistenteRoute
  '/advogado/casos': typeof AdvogadoCasosRoute
  '/advogado/clientes': typeof AdvogadoClientesRouteWithChildren
  '/advogado/dashboard': typeof AdvogadoDashboardRoute
  '/advogado/documentos': typeof AdvogadoDocumentosRoute
  '/advogado/notificacoes': typeof AdvogadoNotificacoesRoute
  '/advogado/processos': typeof AdvogadoProcessosRouteWithChildren
  '/cliente/assistente': typeof ClienteAssistenteRoute
  '/advogado/clientes/$id': typeof AdvogadoClientesIdRoute
  '/advogado/processos/$id': typeof AdvogadoProcessosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advogado'
    | '/cliente'
    | '/login'
    | '/advogado/agenda'
    | '/advogado/assistente'
    | '/advogado/casos'
    | '/advogado/clientes'
    | '/advogado/dashboard'
    | '/advogado/documentos'
    | '/advogado/notificacoes'
    | '/advogado/processos'
    | '/cliente/assistente'
    | '/advogado/clientes/$id'
    | '/advogado/processos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advogado'
    | '/cliente'
    | '/login'
    | '/advogado/agenda'
    | '/advogado/assistente'
    | '/advogado/casos'
    | '/advogado/clientes'
    | '/advogado/dashboard'
    | '/advogado/documentos'
    | '/advogado/notificacoes'
    | '/advogado/processos'
    | '/cliente/assistente'
    | '/advogado/clientes/$id'
    | '/advogado/processos/$id'
  id:
    | '__root__'
    | '/'
    | '/advogado'
    | '/cliente'
    | '/login'
    | '/advogado/agenda'
    | '/advogado/assistente'
    | '/advogado/casos'
    | '/advogado/clientes'
    | '/advogado/dashboard'
    | '/advogado/documentos'
    | '/advogado/notificacoes'
    | '/advogado/processos'
    | '/cliente/assistente'
    | '/advogado/clientes/$id'
    | '/advogado/processos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadoRoute: typeof AdvogadoRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogado': {
      id: '/advogado'
      path: '/advogado'
      fullPath: '/advogado'
      preLoaderRoute: typeof AdvogadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogado/agenda': {
      id: '/advogado/agenda'
      path: '/agenda'
      fullPath: '/advogado/agenda'
      preLoaderRoute: typeof AdvogadoAgendaRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/assistente': {
      id: '/advogado/assistente'
      path: '/assistente'
      fullPath: '/advogado/assistente'
      preLoaderRoute: typeof AdvogadoAssistenteRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/casos': {
      id: '/advogado/casos'
      path: '/casos'
      fullPath: '/advogado/casos'
      preLoaderRoute: typeof AdvogadoCasosRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/clientes': {
      id: '/advogado/clientes'
      path: '/clientes'
      fullPath: '/advogado/clientes'
      preLoaderRoute: typeof AdvogadoClientesRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/dashboard': {
      id: '/advogado/dashboard'
      path: '/dashboard'
      fullPath: '/advogado/dashboard'
      preLoaderRoute: typeof AdvogadoDashboardRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/documentos': {
      id: '/advogado/documentos'
      path: '/documentos'
      fullPath: '/advogado/documentos'
      preLoaderRoute: typeof AdvogadoDocumentosRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/notificacoes': {
      id: '/advogado/notificacoes'
      path: '/notificacoes'
      fullPath: '/advogado/notificacoes'
      preLoaderRoute: typeof AdvogadoNotificacoesRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/advogado/processos': {
      id: '/advogado/processos'
      path: '/processos'
      fullPath: '/advogado/processos'
      preLoaderRoute: typeof AdvogadoProcessosRouteImport
      parentRoute: typeof AdvogadoRoute
    }
    '/cliente/assistente': {
      id: '/cliente/assistente'
      path: '/assistente'
      fullPath: '/cliente/assistente'
      preLoaderRoute: typeof ClienteAssistenteRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/advogado/clientes/$id': {
      id: '/advogado/clientes/$id'
      path: '/$id'
      fullPath: '/advogado/clientes/$id'
      preLoaderRoute: typeof AdvogadoClientesIdRouteImport
      parentRoute: typeof AdvogadoClientesRoute
    }
    '/advogado/processos/$id': {
      id: '/advogado/processos/$id'
      path: '/$id'
      fullPath: '/advogado/processos/$id'
      preLoaderRoute: typeof AdvogadoProcessosIdRouteImport
      parentRoute: typeof AdvogadoProcessosRoute
    }
  }
}

interface AdvogadoClientesRouteChildren {
  AdvogadoClientesIdRoute: typeof AdvogadoClientesIdRoute
}

const AdvogadoClientesRouteChildren: AdvogadoClientesRouteChildren = {
  AdvogadoClientesIdRoute: AdvogadoClientesIdRoute,
}

const AdvogadoClientesRouteWithChildren =
  AdvogadoClientesRoute._addFileChildren(AdvogadoClientesRouteChildren)

interface AdvogadoProcessosRouteChildren {
  AdvogadoProcessosIdRoute: typeof AdvogadoProcessosIdRoute
}

const AdvogadoProcessosRouteChildren: AdvogadoProcessosRouteChildren = {
  AdvogadoProcessosIdRoute: AdvogadoProcessosIdRoute,
}

const AdvogadoProcessosRouteWithChildren =
  AdvogadoProcessosRoute._addFileChildren(AdvogadoProcessosRouteChildren)

interface AdvogadoRouteChildren {
  AdvogadoAgendaRoute: typeof AdvogadoAgendaRoute
  AdvogadoAssistenteRoute: typeof AdvogadoAssistenteRoute
  AdvogadoCasosRoute: typeof AdvogadoCasosRoute
  AdvogadoClientesRoute: typeof AdvogadoClientesRouteWithChildren
  AdvogadoDashboardRoute: typeof AdvogadoDashboardRoute
  AdvogadoDocumentosRoute: typeof AdvogadoDocumentosRoute
  AdvogadoNotificacoesRoute: typeof AdvogadoNotificacoesRoute
  AdvogadoProcessosRoute: typeof AdvogadoProcessosRouteWithChildren
}

const AdvogadoRouteChildren: AdvogadoRouteChildren = {
  AdvogadoAgendaRoute: AdvogadoAgendaRoute,
  AdvogadoAssistenteRoute: AdvogadoAssistenteRoute,
  AdvogadoCasosRoute: AdvogadoCasosRoute,
  AdvogadoClientesRoute: AdvogadoClientesRouteWithChildren,
  AdvogadoDashboardRoute: AdvogadoDashboardRoute,
  AdvogadoDocumentosRoute: AdvogadoDocumentosRoute,
  AdvogadoNotificacoesRoute: AdvogadoNotificacoesRoute,
  AdvogadoProcessosRoute: AdvogadoProcessosRouteWithChildren,
}

const AdvogadoRouteWithChildren = AdvogadoRoute._addFileChildren(
  AdvogadoRouteChildren,
)

interface ClienteRouteChildren {
  ClienteAssistenteRoute: typeof ClienteAssistenteRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteAssistenteRoute: ClienteAssistenteRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadoRoute: AdvogadoRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
